# Site settings
title: "Hacking the Library"
email: steele@osteele.com
description: >
  Let’s create a new kind of Library.

baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://hackingthelibrary.org"
timezone: America/New_York

collections:
  days:
    output: true
    permalink: /day/:path/
  assignments:
    output: true
    permalink: /assignments/:path/

course:
  title: "Special Topics in Computing: Hacking the Library"
  number: "ENGR3599"

defaults:
  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment
  - scope:
      path: ""
      type: days
    values:
      layout: assignment

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
